### ISSUE TITLE
Jasmine fixtures cannot be loaded through Sinatra

### ISSUE THREAD

**Issue by timrobertson0122** [makersacademy/issues#1]
@tansaku 

### Link to repo - https://github.com/timrobertson0122/thermostat/tree/load-fixtures-bug

As per the attached screenshots I'm running my Thermostat app through Sinatra (runs fine) however Jasmine can no longer find my UI to run my tests and I have no idea what I need to change/how I need to restructure to get this to work.

N.B. Ptolemy and I copied my /views inside /public and renamed index.erb to index.erb.html but to no positive effect. 

Totally confused by it all tbh....

![specrunner](https://cloud.githubusercontent.com/assets/2273224/7911048/b3c73f28-0851-11e5-96cc-0ac96dce689c.png)
![jasmine fixtures](https://cloud.githubusercontent.com/assets/2273224/7911052/b60135e6-0851-11e5-9b8e-f7e712c1e426.png)
![tree](https://cloud.githubusercontent.com/assets/2273224/7911054/b8829f58-0851-11e5-9624-68c6148ecb01.png)

**Comment by ptolemybarnes** [comment]
Github link? Really hard to debug otherwise.

**Comment by tansaku** [comment]
Hi @timrobertson0122 I'm taking a look now ...

**Comment by tansaku** [comment]
it all seems to work for me ...

![all working](https://www.dropbox.com/s/8plmsjhhsqo91er/Screenshot%202015-06-01%2015.04.28.png?dl=1)

**Comment by tansaku** [comment]
here's how I'm running it:

```
[tansaku@Samuels-MBP:~/Documents/Github/MakersAcademy/Students/April2015/TimRobertson/thermostat (master)]$ 
→ rackup & 
[1] 45227
[tansaku@Samuels-MBP:~/Documents/Github/MakersAcademy/Students/April2015/TimRobertson/thermostat (master)]$  open http://localhost:9292/SpecRunner.html?

```

**Comment by Gwasanaethau** [comment]
Hey, a Rōnin here…Ptolemy directed us to the issues page to give yous a hand if you needed it. I can concur with tansaku…seems to be working OK here too! I tried running locally (from filesystem) and via localhost:9292.

**Comment by timrobertson0122** [comment]
Thanks both. It works on master branch but the most recent work is on the api branch where I've added the weather api and re-structured a little bit - it won't work on that branch.........

**Comment by tansaku** [comment]
aha, thanks @timrobertson0122 - sorry - let me check that branch then ...

**Comment by Gwasanaethau** [comment]
I did the same, sorry!

**Comment by tansaku** [comment]
ok, so I have partially fixed it

**Comment by tansaku** [comment]
the problem is that your fixture loading code:

```
  beforeEach(function() {
    jasmine.getFixtures().fixturesPath = '.';
    loadFixtures('index.erb.html');
    $.holdReady(false);
  });
```

is trying to load the index.erb.html file **relative** to where the SpecRunner.html file is located.  Since index.erb.html is not in the features directory where the SpecRunner.html file is, the index.erb.html file cannot be loaded, and hence you get the error:

```
Error: Fixture could not be loaded: ./index.erb.html (status: error, message: undefined)
```

note the "./" at the start of the "./index.erb.html", which is a hint that the problem is related to file paths.

So, I have the solution, which I could just give you, and I certainly will if you demand it, but can you work out for yourself the relative path that you need to specify in `loadFixtures('index.erb.html');` so that the fixture can be found?

**Comment by tansaku** [comment]
I also note that to access the SpecRunner.html I have to go to the following link:

http://localhost:9292/JS/SpecRunner.html?

There is another conversation we could have about the layout of your files and directories ... :-)

**Comment by timrobertson0122** [comment]
This particular issue has now been resolved, many thanks.

**Comment by tansaku** [comment]
I think the interesting thing about the file structure here is that in a "normal" app, we'd have the javascripts in a 'public/javascripts' directory and we would not normally have the specs and the fixtures and the SpecRunner.html in there in that we'd probably be running our jasmine tests through a rake task.  

Given this is a toy app and we want easy access to our SpecRunner.html I guess it is fair enough.  However I'm a little concerned about the proliferation of different views through the app - I believe the erb files should all be in a single place - probably best in 'app/views' given your current structure ...  I think there's danger of things being a little unDRY

**Comment by timrobertson0122** [comment]
@tansaku Ptolemy and I copied my /views inside /public and renamed index.erb to index.erb.html to try to get the fixtures. If I try ```describe('Interface', function() {
  
  beforeEach(function() {
    jasmine.getFixtures().fixturesPath = 'app/views/';
    loadFixtures('index.erb');
    $.holdReady(false);
  });
```
I get the following error:
```
16 specs, 7 failures
Spec List | Failures
Interface displays default temperature
Error: Fixture could not be loaded: app/views/index.erb (status: error, message: undefined)
Error: Fixture could not be loaded: app/views/index.erb (status: error, message: undefined)
    at Object.<anonymous> (http://localhost:9292/JS/lib/jasmine-jquery.js:133:17)
    at fire (http://localhost:9292/JS/lib/jquery.js:3099:30)
    at Object.self.add (http://localhost:9292/JS/lib/jquery.js:3145:7)
    at jasmine.Fixtures.loadFixtureIntoCache_ (http://localhost:9292/JS/lib/jasmine-jquery.js:132:10)
    at jasmine.Fixtures.getFixtureHtml_ (http://localhost:9292/JS/lib/jasmine-jquery.js:115:12)
    at jasmine.Fixtures.read (http://localhost:9292/JS/lib/jasmine-jquery.js:77:28)
    at jasmine.Fixtures.load (http://localhost:9292/JS/lib/jasmine-jquery.js:65:37)
    at jasmine.Fixtures.proxyCallTo_ (http://localhost:9292/JS/lib/jasmine-jquery.js:161:29)
    at window.loadFixtures (http://localhost:9292/JS/lib/jasmine-jquery.js:782:27)
    at Object.<anonymous> (http://localhost:9292/JS/spec/features/InterfaceSpec.js:5:5)
```

Is there a 'best-practice' I can compare with? Would like to figure out how to run my Jasmine tests via a rake task also.
