### ISSUE TITLE
Bowling Challenge - Jasmine - Testing across different prototypes?!

### ISSUE THREAD

**Issue by timrobertson0122** [makersacademy/issues#4]
So I have a Frame proto which puts each roll into a [rolls] array and a Scorecard proto which puts each frame array into a [frames] array. I'm now trying to test that the Scorecard can pick out the value of a particular roll from a particular frame, and have written the following:

```
it("knows the score of a particular ball in a particular frame", function() {
      scorecard.addFrame({total : function() { return 1} });
      scorecard.addFrame({total : function() { return 1} });
      expect(scorecard.frames[0].rolls[0]).toEqual(1);
    });
```

This is based off the following, working test:
```
it("can calculate a total of a series of frames", function(){
      scorecard.addFrame({total : function() { return 3} });
      scorecard.addFrame({total : function() { return 3} });
      expect(scorecard.total()).toEqual(6);
    });
```

Following screenshot shows my results (ignore the console error) Works in console, Jasmine doesn't like it and I'm not sure if it's syntax or I'm just doing something mental:

![screen shot 2015-06-03 at 21 17 22](https://cloud.githubusercontent.com/assets/2273224/7970655/7699ad6a-0a37-11e5-922e-493da2163b2f.png)

@silvabox @spike01 @ptolemybarnes  Thanks!

**Comment by ptolemybarnes** [comment]
Looks like ur doubling frames in that test but your frame double doesn't have a #rolls property
